{
  "code": 400,
  "apierror": {
    "uuaa": "servicio resolver reparto",
    "version": "1.0.26-RC-SNAPSHOT",
    "status": "BAD_REQUEST",
    "errorCode": "METHOD_ARGUMENT_NOT_VALID",
    "timestamp": "10-04-2023 04:35:27",
    "message": "Validation failed for argument [0] in public es.correos.met.arquitectura.dto.DataDTO<es.correos.eco.libreria.dto.item.ItemDTO> es.correos.hades.resolver_reparto.controller.DeliveryController.registerDelivery(es.correos.hades.resolver_reparto.dto.DeliveryRequestDTO) throws es.correos.hades.resolver_reparto.exceptions.DeliveryBadRequestException,es.correos.hades.resolver_reparto.exceptions.DeliveryExistsConflictException,es.correos.hades.resolver_reparto.exceptions.DeliveryNotFoundException,es.correos.hades.resolver_reparto.exceptions.IncidenceResolutionNotFoundException,es.correos.hades.resolver_reparto.exceptions.MaxDeliveryAttemptNotFoundException,es.correos.hades.resolver_reparto.exceptions.IncidentTypeNotFoundException,es.correos.hades.resolver_reparto.exceptions.ProductNotFoundException: [Field error in object 'deliveryRequestDTO' on field 'itemsQuantity': rejected value [31001]; codes [Digits.deliveryRequestDTO.itemsQuantity,Digits.itemsQuantity,Digits.java.lang.Integer,Digits]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [deliveryRequestDTO.itemsQuantity,itemsQuantity]; arguments []; default message [itemsQuantity],0,4]; default message [Max 4 digits, items quantity]] ",
    "subErrors": [
      {
        "object": "deliveryRequestDTO",
        "field": "itemsQuantity",
        "rejectedValue": 31001,
        "message": "Max 4 digits, items quantity"
      }
    ],
    "errors": [
      
    ]
  }
}